from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime
import io

def generate_medical_report(user, diagnosis, risk_level):
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Header
    p.setFont("Helvetica-Bold", 20)
    p.drawCentredString(width/2, height - (1 * inch), "AI Medical Diagnosis Assistant")
    
    p.setFont("Helvetica", 10)
    p.drawCentredString(width/2, height - (1.3 * inch), "Generated Medical Report")
    p.line(0.5 * inch, height - (1.5 * inch), 7.5 * inch, height - (1.5 * inch))

    # Patient Details
    y = height - (2.0 * inch)
    p.setFont("Helvetica-Bold", 12)
    p.drawString(1 * inch, y, "Patient Information:")
    p.setFont("Helvetica", 11)
    p.drawString(1 * inch, y - 0.2*inch, f"Name: {user.username}")
    p.drawString(1 * inch, y - 0.4*inch, f"Email: {user.email}")
    p.drawString(1 * inch, y - 0.6*inch, f"Report Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}")

    # Diagnosis Results
    y -= 1.2 * inch
    p.setFont("Helvetica-Bold", 12)
    p.drawString(1 * inch, y, "Diagnosis Summary:")
    
    p.setFont("Helvetica", 11)
    p.drawString(1 * inch, y - 0.3 * inch, f"Risk Score: {diagnosis.risk_score}")
    
    # Risk Level with Color
    risk_color = colors.green
    if risk_level['label'] == 'Medium': risk_color = colors.orange
    if risk_level['label'] == 'High': risk_color = colors.red
    
    p.drawString(1 * inch, y - 0.5 * inch, "Risk Level: ")
    p.setFillColor(risk_color)
    p.drawString(2 * inch, y - 0.5 * inch, risk_level['label'])
    p.setFillColor(colors.black)
    
    p.drawString(1 * inch, y - 0.7 * inch, f"Classification: {risk_level['description']}")

    # Symptoms
    y -= 1.2 * inch
    p.setFont("Helvetica-Bold", 12)
    p.drawString(1 * inch, y, "Symptoms Reported:")
    p.setFont("Helvetica", 11)
    symptoms = diagnosis.get_symptoms()
    sy = y - 0.3 * inch
    for s, sev in symptoms.items():
        p.drawString(1.2 * inch, sy, f"- {s.replace('_', ' ').title()} (Severity: {sev})")
        sy -= 0.2 * inch
        if sy < 1 * inch: # Page break if too many
            p.showPage()
            sy = height - 1 * inch

    # Top Predictions
    y = sy - 0.5 * inch
    p.setFont("Helvetica-Bold", 12)
    p.drawString(1 * inch, y, "Predicted Diseases:")
    p.setFont("Helvetica", 11)
    predictions = diagnosis.get_predictions()
    py = y - 0.3 * inch
    for pred in predictions:
        p.drawString(1.2 * inch, py, f"- {pred['disease']}: {pred['probability']}% confidence")
        py -= 0.2 * inch

    # Footer
    p.setFont("Helvetica-Oblique", 8)
    p.drawString(1 * inch, 0.5 * inch, "Disclaimer: This report is generated by an AI assistant and should not replace professional medical advice.")
    p.drawString(1 * inch, 0.4 * inch, "Please consult with a qualified healthcare provider for any medical concerns.")

    p.save()
    buffer.seek(0)
    return buffer
